events {}

http {
    server {
        listen 80;

        location / {
            # Strip leading slash, remainder is the target URL
            # Usage: http://<relay-ip>/http://example.com
            proxy_pass https://saxwfm8q8f.execute-api.us-east-2.amazonaws.com/prod/proxy/;
            proxy_ssl_server_name on;
            proxy_set_header Host saxwfm8q8f.execute-api.us-east-2.amazonaws.com;
        }
    }
}
